name: Build and deploy production images

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.francois.poguet.com
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set the right docker-compose file for tests
        run: mv .github/test/docker-compose.test.yml ./docker-compose.yml

      - name: Install php dependencies
        run: docker-compose run -T php composer install

      - name: Run tests
        run: docker-compose run -T php php ./bin/phpunit

  build-images:
    name: Build & push images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.francois.poguet.com
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push php image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/php/Dockerfile.prod
          context: .
          push: true
          tags: docker.francois.poguet.com/symfony5-php-prod

      - name: Build & push nginx image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/nginx/Dockerfile.prod
          context: .
          push: true
          tags: docker.francois.poguet.com/symfony5-nginx-prod

      - name: Send webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.SYMFONY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.SYMFONY_WEBHOOK_SECRET }}
