name: Run the server tests

on:
  pull_request:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.francois.poguet.com
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set the .env file
        run: mv .github/test/.env ./.env

      - name: Set the docker-compose file
        run: mv .github/test/docker-compose.test.yml ./docker-compose.yml

      - name: Install php dependencies
        run: docker-compose run -T php composer install

      - name: Run tests
        run: docker-compose run -T php php ./bin/phpunit
