name: Run the server tests

on:
  pull_request:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.francois.poguet.com
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install php dependencies
        run: docker-compose -f docker-compose.test.yml run --rm -T php composer install

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run --rm  -T php php ./bin/phpunit
